<?php

declare(strict_types=1);

/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 * DO NOT EDIT THIS FILE!
 *
 * It's auto-generated by sonata-project/dev-kit package.
 */

/*
 * fix encoding issue while running text on different host with different locale configuration
 */

use Sonata\DoctrineMongoDBAdminBundle\Tests\App\AppKernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Output\NullOutput;

setlocale(LC_ALL, 'en_US.UTF-8');

if (file_exists($file = __DIR__.'/autoload.php')) {
    require_once $file;
} elseif (file_exists($file = __DIR__.'/autoload.php.dist')) {
    require_once $file;
}

/*
 * try to get Symfony's PHPUnit Bridge
 */
$files = array_filter([
    __DIR__.'/../vendor/symfony/symfony/src/Symfony/Bridge/PhpUnit/bootstrap.php',
    __DIR__.'/../vendor/symfony/phpunit-bridge/bootstrap.php',
    __DIR__.'/../../../../vendor/symfony/symfony/src/Symfony/Bridge/PhpUnit/bootstrap.php',
    __DIR__.'/../../../../vendor/symfony/phpunit-bridge/bootstrap.php',
], 'file_exists');

if ($files) {
    require_once current($files);
}

$publicDir = __DIR__.'/App/public';
$_SERVER['PANTHER_WEB_SERVER_DIR'] = $publicDir;

$application = new Application(new AppKernel());
$application->setAutoExit(false);

// Load fixtures of the AppTestBundle
$input = new ArrayInput([
    'command' => 'doctrine:mongodb:fixtures:load',
    '--no-interaction' => false,
]);
$application->run($input, new ConsoleOutput());

// Install Assets
$input = new ArrayInput([
    'command' => 'assets:install',
    'target' => $publicDir,
    '--symlink' => true,
]);
$application->run($input, new NullOutput());
